u = (2:5)'
l = ((100:103) *.01 - 1)'
B = eye(4);
g = 4 * ones(4,1);
iterate_z = ones(4,1)
direction_d = ones(4,1);
num_matvec = 0;
[x,num_matvec] = tau_line_search(iterate_z, ...
				       direction_d,...
				       g,...
				       B,...
				       u,l,...
				       num_matvec)

u = (2:5)'
l = ((100:103) *.01 - 1)'
B = eye(4);
g = -4 * ones(4,1);
iterate_z = ones(4,1)
direction_d = ones(4,1);
num_matvec = 0;
[x,num_matvec] = tau_line_search(iterate_z, ...
				       direction_d,...
				       g,...
				       B,...
				       u,l,...
				       num_matvec)